name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.TGM_PRIV_KEY }}
      with:
        args: "$GITHUB_REPOSITORY $GITHUB_BRANCH 'dlangheiter-tgm/test' $GITHUB_BRANCH"
